/* 
File: ~/DataCommerceDB/scripts/insert_products.sql
Purpose: Injects all products into the products table.
*/

INSERT INTO products (name, price, category) VALUES ('Spicy Avocado Salsa', 4.49, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Under Desk Footrest', 29.99, 'Office');
INSERT INTO products (name, price, category) VALUES ('Peanut Butter Chocolate Clusters', 2.99, 'Food - Desserts');
INSERT INTO products (name, price, category) VALUES ('Silicone Baking Mat Set', 24.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Tomato Basil Soup', 3.49, 'Food - Canned Goods');
INSERT INTO products (name, price, category) VALUES ('Chickpeas', 1.29, 'Food - Canned Goods');
INSERT INTO products (name, price, category) VALUES ('Fitness Smartwatch', 99.99, 'Wearable Tech');
INSERT INTO products (name, price, category) VALUES ('Organic Coconut Flakes', 3.49, 'Food - Baking');
INSERT INTO products (name, price, category) VALUES ('Cinnamon Raisin Bread', 3.79, 'Food - Bakery');
INSERT INTO products (name, price, category) VALUES ('Lentil Soup', 2.49, 'Food - Canned Goods');
INSERT INTO products (name, price, category) VALUES ('Banana Chips', 1.99, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('Lemon Dill Chicken Skewers', 9.99, 'Food - Meat');
INSERT INTO products (name, price, category) VALUES ('Rolling Cooler', 59.99, 'Outdoor');
INSERT INTO products (name, price, category) VALUES ('Vegetable Lasagna', 6.99, 'Food - Frozen Foods');
INSERT INTO products (name, price, category) VALUES ('Balsamic Vinaigrette', 2.69, 'Food - Dressings');
INSERT INTO products (name, price, category) VALUES ('Essential White Button-Up', 44.99, 'Clothing - Shirts');
INSERT INTO products (name, price, category) VALUES ('Non-Stick Grill Mat', 19.99, 'Outdoor');
INSERT INTO products (name, price, category) VALUES ('Buffalo Cauliflower Wings', 6.99, 'Food - Frozen Foods');
INSERT INTO products (name, price, category) VALUES ('Black Bean & Corn Salad', 3.99, 'Food - Salads');
INSERT INTO products (name, price, category) VALUES ('Recipe Book Stand', 22.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Folding Pocket Knife', 24.99, 'Tools');
INSERT INTO products (name, price, category) VALUES ('Coconut Rice', 2.29, 'Food - Frozen');
INSERT INTO products (name, price, category) VALUES ('Magic Color-Changing Mug', 14.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Yoga Mat', 25, 'Fitness');
INSERT INTO products (name, price, category) VALUES ('Spaghetti Sauce', 2.99, 'Food - Canned Goods');
INSERT INTO products (name, price, category) VALUES ('Smartphone Gimbal', 89.99, 'Electronics');
INSERT INTO products (name, price, category) VALUES ('Travel Pillow', 22.99, 'Travel');
INSERT INTO products (name, price, category) VALUES ('Camping Lantern', 34.99, 'Outdoor');
INSERT INTO products (name, price, category) VALUES ('Vegan Tacos', 7.49, 'Food - Frozen Foods');
INSERT INTO products (name, price, category) VALUES ('Coconut Macaroons', 4.99, 'Food - Confectionery');
INSERT INTO products (name, price, category) VALUES ('Electric Knife', 39.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Kale Caesar Salad Kit', 5.99, 'Food - Salads');
INSERT INTO products (name, price, category) VALUES ('Artisan Pickles', 2.49, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Electric Heating Pad', 20.99, 'Health');
INSERT INTO products (name, price, category) VALUES ('Spicy Snack Mix', 4.99, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('Cocktail Shaker and Mixing Glass Set', 39.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Granola', 4.79, 'Food - Breakfast');
INSERT INTO products (name, price, category) VALUES ('Air Mattress', 49.99, 'Outdoor');
INSERT INTO products (name, price, category) VALUES ('Crafting Kit', 29.99, 'Art Supplies');
INSERT INTO products (name, price, category) VALUES ('Strawberry Rhubarb Jam', 4.29, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Rustic Italian Bread', 3.59, 'Food - Bakery');
INSERT INTO products (name, price, category) VALUES ('Cinnamon Spiced Almonds', 5.99, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('Garden Vegetable Soup', 3.29, 'Food - Canned Goods');
INSERT INTO products (name, price, category) VALUES ('Baked Falafel Balls', 5.99, 'Food - Frozen Vegetables');
INSERT INTO products (name, price, category) VALUES ('Oversized Denim Shirt', 49.99, 'Clothing - Shirts');
INSERT INTO products (name, price, category) VALUES ('Mediterranean Chickpea Salad', 5.99, 'Food - Salads');
INSERT INTO products (name, price, category) VALUES ('Bamboo Cotton Tank Top', 22.99, 'Clothing - Tops');
INSERT INTO products (name, price, category) VALUES ('Buffalo Wing Sauce', 3.99, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Casual Long Cardigan', 45.99, 'Clothing - Outerwear');
INSERT INTO products (name, price, category) VALUES ('Kettle Corn Popcorn', 2.99, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('Portable Leaf Blower', 149.99, 'Outdoor');
INSERT INTO products (name, price, category) VALUES ('Air Mattress', 49.99, 'Outdoor');
INSERT INTO products (name, price, category) VALUES ('Sweet and Sour Sauce', 2.79, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Sweet and Sour Sauce', 2.79, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Grilled Vegetable Medley', 4.49, 'Food - Vegetables');
INSERT INTO products (name, price, category) VALUES ('Elderberry Syrup Kit', 22.99, 'Health');
INSERT INTO products (name, price, category) VALUES ('Cinnamon Roll Protein Bar', 2.99, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('Crispy Kale Chips', 2.99, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('White Rice', 1.49, 'Food - Grains');
INSERT INTO products (name, price, category) VALUES ('Lemon Dill Salmon', 9.99, 'Food - Seafood');
INSERT INTO products (name, price, category) VALUES ('Corn Tortillas', 2.49, 'Food - Bakery');
INSERT INTO products (name, price, category) VALUES ('Fried Rice', 4.29, 'Food - Frozen Foods');
INSERT INTO products (name, price, category) VALUES ('Field Journal', 14.99, 'Books');
INSERT INTO products (name, price, category) VALUES ('Honey Sesame Chicken Mix', 8.99, 'Food - Frozen Meals');
INSERT INTO products (name, price, category) VALUES ('Fresh Lemons', 0.75, 'Food - Fresh Produce');
INSERT INTO products (name, price, category) VALUES ('Sporty Slide Sandals', 24.99, 'Clothing - Footwear');
INSERT INTO products (name, price, category) VALUES ('Sporty Cap', 15.99, 'Clothing - Accessories');
INSERT INTO products (name, price, category) VALUES ('Electric Wax Warmer', 22.99, 'Home');
INSERT INTO products (name, price, category) VALUES ('Insulated Sport Tumbler', 22.99, 'Fitness');
INSERT INTO products (name, price, category) VALUES ('Chipotle Sauce', 3.29, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Electric Griddle', 54.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Coconut Cream Pie Mix', 4.99, 'Food - Baking');
INSERT INTO products (name, price, category) VALUES ('Vegan Caesar Dressing', 3.99, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Fruit Infuser Water Bottle', 15.99, 'Fitness');
INSERT INTO products (name, price, category) VALUES ('Vintage Graphic Tee', 25.99, 'Clothing - Tops');
INSERT INTO products (name, price, category) VALUES ('Fresh Cilantro', 1.49, 'Food - Produce');
INSERT INTO products (name, price, category) VALUES ('Stainless Steel Travel Mug', 19.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Stuffed Bell Peppers', 5.99, 'Food - Frozen Meals');
INSERT INTO products (name, price, category) VALUES ('Compressible Packing Cubes', 29.99, 'Travel');
INSERT INTO products (name, price, category) VALUES ('Backpack', 49.99, 'Accessories');
INSERT INTO products (name, price, category) VALUES ('Pistachios', 6.99, 'Food - Nuts');
INSERT INTO products (name, price, category) VALUES ('Sweet and Spicy Barbecue Sauce', 3.99, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Portable Pet Stroller', 89.99, 'Pets');
INSERT INTO products (name, price, category) VALUES ('Electric Milk Frother', 19.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Tandoori Chicken Skewers', 7.99, 'Food - Meat');
INSERT INTO products (name, price, category) VALUES ('Ultra-Thin Laptop Sleeve', 19.99, 'Accessories');
INSERT INTO products (name, price, category) VALUES ('Electric Meat Grinder', 89.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Coconut Cream Pie Yogurt', 1.99, 'Food - Dairy Alternatives');
INSERT INTO products (name, price, category) VALUES ('Sweetened Condensed Milk', 1.89, 'Food - Baking Goods');
INSERT INTO products (name, price, category) VALUES ('Toilet Paper (12 rolls)', 8.99, 'Food - Household');
INSERT INTO products (name, price, category) VALUES ('DIY Organic Gardening Kit', 39.99, 'Garden');
INSERT INTO products (name, price, category) VALUES ('Honey Sesame Chicken', 8.99, 'Food - Frozen Food');
INSERT INTO products (name, price, category) VALUES ('Mini Air Purifier', 49.99, 'Health');
INSERT INTO products (name, price, category) VALUES ('Electric Griddle with Removable Plates', 59.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Coconut Chips', 3.59, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('Chili Con Carne Mix', 2.99, 'Food - Spices & Seasonings');
INSERT INTO products (name, price, category) VALUES ('Classic Pumps', 64.99, 'Clothing - Footwear');
INSERT INTO products (name, price, category) VALUES ('Chickpea Snack Mix', 3.49, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('Manual Coffee Grinder', 22.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Trendy Bomber Jacket', 69.99, 'Clothing - Outerwear');
INSERT INTO products (name, price, category) VALUES ('Scented Candle Set', 24.99, 'Home');
INSERT INTO products (name, price, category) VALUES ('Potting Soil', 15.99, 'Garden');
INSERT INTO products (name, price, category) VALUES ('Coconut Curry Chicken', 9.99, 'Food - Frozen Foods');
INSERT INTO products (name, price, category) VALUES ('Coconut Oil Spray', 4.99, 'Food - Cooking Oils');
INSERT INTO products (name, price, category) VALUES ('Pressure Washer Accessories Kit', 39.99, 'Home Improvement');
INSERT INTO products (name, price, category) VALUES ('Organic Honeycrisp Apples', 1.99, 'Food - Fruits');
INSERT INTO products (name, price, category) VALUES ('Chickpea Flour', 3.29, 'Food - Baking');
INSERT INTO products (name, price, category) VALUES ('Lemon Basil Pasta Sauce', 4.99, 'Food - Sauces');
INSERT INTO products (name, price, category) VALUES ('High-Quality Yoga Block', 12.99, 'Fitness');
INSERT INTO products (name, price, category) VALUES ('Berry Smoothie Mix', 4.99, 'Food - Frozen Foods');
INSERT INTO products (name, price, category) VALUES ('Sweet Chili Thai Sauce', 3.49, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Red Lentil Pasta', 3.99, 'Food - Pasta');
INSERT INTO products (name, price, category) VALUES ('Dishwasher Safe Cutting Board', 22.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Comfortable Jogger Pants', 29.99, 'Clothing - Bottoms');
INSERT INTO products (name, price, category) VALUES ('Handheld Garment Steamer', 34.99, 'Home');
INSERT INTO products (name, price, category) VALUES ('Wine Decanter', 34.99, 'Home');
INSERT INTO products (name, price, category) VALUES ('Children''s Musical Instrument Set', 39.99, 'Toys');
INSERT INTO products (name, price, category) VALUES ('Decorative Throw Pillows', 29.99, 'Home');
INSERT INTO products (name, price, category) VALUES ('Beef Jerky', 5.99, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('Lemon Dill Salmon', 9.99, 'Food - Seafood');
INSERT INTO products (name, price, category) VALUES ('Gingerbread House Kit', 6.99, 'Food - Baking');
INSERT INTO products (name, price, category) VALUES ('Strawberry Banana Smoothie Pack', 4.99, 'Food - Frozen');
INSERT INTO products (name, price, category) VALUES ('Streaming Device', 49.99, 'Electronics');
INSERT INTO products (name, price, category) VALUES ('Outdoor Portable Fire Pit', 149.99, 'Outdoor');
INSERT INTO products (name, price, category) VALUES ('Organic Brown Rice Cakes', 3.99, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('Fleece Lined Leggings', 29.99, 'Clothing');
INSERT INTO products (name, price, category) VALUES ('Chicken Fajita Kit', 8.99, 'Food - Prepared Foods');
INSERT INTO products (name, price, category) VALUES ('Feta Cheese', 4.99, 'Food - Dairy');
INSERT INTO products (name, price, category) VALUES ('Car Seat Organizer', 14.99, 'Automotive');
INSERT INTO products (name, price, category) VALUES ('Peanut Butter Chocolate Clusters', 2.99, 'Food - Desserts');
INSERT INTO products (name, price, category) VALUES ('Mini Air Purifier', 49.99, 'Health');
INSERT INTO products (name, price, category) VALUES ('Portable Speaker Stand', 39.99, 'Audio');
INSERT INTO products (name, price, category) VALUES ('Canvas High-Top Sneakers', 49.99, 'Clothing - Footwear');
INSERT INTO products (name, price, category) VALUES ('Children''s Gardening Set', 19.99, 'Toys');
INSERT INTO products (name, price, category) VALUES ('Indian Curry Sauce', 3.69, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Video Camera', 199, 'Electronics');
INSERT INTO products (name, price, category) VALUES ('Safety Goggles', 14.99, 'Safety');
INSERT INTO products (name, price, category) VALUES ('Chocolate Chip Cookie Dough', 5.49, 'Food - Baking');
INSERT INTO products (name, price, category) VALUES ('Classic Chicken Noodle Soup', 3.49, 'Food - Canned Goods');
INSERT INTO products (name, price, category) VALUES ('Blender Bottle', 12.99, 'Fitness');
INSERT INTO products (name, price, category) VALUES ('Digital Food Thermometer', 19.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Electric Hot Pot', 49.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Rain Jacket', 64.99, 'Clothing');
INSERT INTO products (name, price, category) VALUES ('Almond Butter Crunch Bar', 1.99, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('Red Lentil Pasta', 3.99, 'Food - Pasta');
INSERT INTO products (name, price, category) VALUES ('Motion Sensor Light', 19.99, 'Home');
INSERT INTO products (name, price, category) VALUES ('Nutty Granola Clusters', 2.49, 'Food - Cereal');
INSERT INTO products (name, price, category) VALUES ('LED Camping Lantern with USB Charging', 34.99, 'Outdoor');
INSERT INTO products (name, price, category) VALUES ('Chocolate Syrup', 2.99, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Organic Sweet Potatoes', 1.99, 'Food - Produce');
INSERT INTO products (name, price, category) VALUES ('Peanut Butter Granola', 4.99, 'Food - Breakfast');
INSERT INTO products (name, price, category) VALUES ('Granola', 4.79, 'Food - Breakfast');
INSERT INTO products (name, price, category) VALUES ('Magnetic Spice Jars', 24.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Quinoa Salad', 5.99, 'Food - Prepared Foods');
INSERT INTO products (name, price, category) VALUES ('Multi-Purpose Plant Care Tool', 24.99, 'Garden');
INSERT INTO products (name, price, category) VALUES ('Zesty Cilantro Lime Dressing', 3.29, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Protein Powder', 44.99, 'Fitness');
INSERT INTO products (name, price, category) VALUES ('Chipotle Lime Salsa', 3.99, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Spinach and Cheese Stuffed Shells', 5.99, 'Food - Frozen Meals');
INSERT INTO products (name, price, category) VALUES ('Rain Jacket', 64.99, 'Clothing');
INSERT INTO products (name, price, category) VALUES ('Maxi Wrap Dress', 49.99, 'Clothing - Dresses');
INSERT INTO products (name, price, category) VALUES ('Noise Cancelling Ear Muffs', 24.99, 'Safety');
INSERT INTO products (name, price, category) VALUES ('Coconut Chips', 3.59, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('Smartphone Gimbal Stabilizer', 89.99, 'Photography');
INSERT INTO products (name, price, category) VALUES ('Slingback Sandals', 29.99, 'Clothing - Footwear');
INSERT INTO products (name, price, category) VALUES ('Dog Collar', 15.99, 'Pets');
INSERT INTO products (name, price, category) VALUES ('Rechargeable Electric Screwdriver', 39.99, 'Tools');
INSERT INTO products (name, price, category) VALUES ('Cinnamon Ice Cream', 4.99, 'Food - Frozen Desserts');
INSERT INTO products (name, price, category) VALUES ('Electric Stir Fry Pan', 49.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Apple Cinnamon Breakfast Muffins', 3.49, 'Food - Bakery');
INSERT INTO products (name, price, category) VALUES ('Peanut Butter Chocolate Chip Bars', 4.59, 'Food - Snacks');
INSERT INTO products (name, price, category) VALUES ('Vegetable Curry', 5.99, 'Food - Frozen Foods');
INSERT INTO products (name, price, category) VALUES ('Outdoor String Lights', 24.99, 'Outdoor');
INSERT INTO products (name, price, category) VALUES ('Fitness Resistance Bands Set', 34.99, 'Fitness');
INSERT INTO products (name, price, category) VALUES ('Herbal Tea Infuser', 9.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Graphic Tee', 19.99, 'Clothing');
INSERT INTO products (name, price, category) VALUES ('Classic Leather Wallet', 34.99, 'Clothing - Accessories');
INSERT INTO products (name, price, category) VALUES ('Outdoor Inflatable Pool', 149.99, 'Outdoor');
INSERT INTO products (name, price, category) VALUES ('Smartphone Tripod', 29.99, 'Photography');
INSERT INTO products (name, price, category) VALUES ('Zucchini Noodles', 3.99, 'Food - Vegetables');
INSERT INTO products (name, price, category) VALUES ('Hibiscus Tea Bags', 3.79, 'Food - Beverages');
INSERT INTO products (name, price, category) VALUES ('Tahini', 5.49, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Wall-Mounted Wine Rack', 39.99, 'Home');
INSERT INTO products (name, price, category) VALUES ('Comfort Flats', 44.99, 'Clothing - Shoes');
INSERT INTO products (name, price, category) VALUES ('Almond Milk Yogurt', 1.99, 'Food - Dairy Alternatives');
INSERT INTO products (name, price, category) VALUES ('Himalayan Salt Grinder', 4.99, 'Food - Spices');
INSERT INTO products (name, price, category) VALUES ('Wireless Security Camera', 109.99, 'Home');
INSERT INTO products (name, price, category) VALUES ('Antique Style Clock', 39.99, 'Home');
INSERT INTO products (name, price, category) VALUES ('Smartphone Tripod', 29.99, 'Photography');
INSERT INTO products (name, price, category) VALUES ('Organic Tomato Ketchup', 3.49, 'Food - Condiments');
INSERT INTO products (name, price, category) VALUES ('Foldable Yoga Mat Carry Bag', 18.99, 'Fitness');
INSERT INTO products (name, price, category) VALUES ('Spice Rack', 39.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Yoga Strap', 12.99, 'Fitness');
INSERT INTO products (name, price, category) VALUES ('Sketchbook', 14.99, 'Art Supplies');
INSERT INTO products (name, price, category) VALUES ('Rice Noodles', 3.49, 'Food - Grains');
INSERT INTO products (name, price, category) VALUES ('Sturdy Bookends', 22.99, 'Office');
INSERT INTO products (name, price, category) VALUES ('Shredded Cheese', 4.29, 'Food - Dairy');
INSERT INTO products (name, price, category) VALUES ('Kitchen Knife Sharpening System', 39.99, 'Kitchen');
INSERT INTO products (name, price, category) VALUES ('Decorative Throw Blanket', 39.99, 'Home');
INSERT INTO products (name, price, category) VALUES ('Coconut Rice', 2.29, 'Food - Frozen');
